language: python

python:
  # - 3.5  # Commented out because it complains about "Exception: No database connector found for /tmp/tmppd4goq40/test_tables.h5"
  - 3.6

before_install:
  # Install datasette dependencies
  - pip install pytest aiohttp beautifulsoup4

script:
  - python setup.py install
  - pytest
